[build]
builder = "RAILPACK"

[deploy]
startCommand = "sh -c 'flask --app newsletter db upgrade && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 60 --log-level info --access-logfile - --error-logfile - --capture-output'"