"""removed html content col

Revision ID: 3105794bae58
Revises: a3b4a6d9457d
Create Date: 2026-04-28 13:44:06.364215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3105794bae58'
down_revision = 'a3b4a6d9457d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_list', schema=None) as batch_op:
        batch_op.drop_column('html_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_content', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
