"""initial

Revision ID: 80bb66036f63
Revises: 
Create Date: 2026-04-15 16:59:46.995323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bb66036f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('pw_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('newsletter_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.Column('email_content', sa.Text(), nullable=False),
    sa.Column('sent_to_users', sa.Integer(), nullable=False),
    sa.Column('datetime_sent', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('datetime_joined', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_secret', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('unsubscribe_secret')
    )
    op.create_table('newsletter_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('datetime_sent', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','sent','failed','opened')", name='check_status'),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter_list.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['newsletter_users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsletter_id', 'user_email', name='unique_delivery')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_deliveries')
    op.drop_table('newsletter_users')
    op.drop_table('newsletter_list')
    op.drop_table('admins')
    # ### end Alembic commands ###
