"""general updates

Revision ID: a3b4a6d9457d
Revises: d37218fbe654
Create Date: 2026-04-28 08:33:53.365911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b4a6d9457d'
down_revision = 'd37218fbe654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_admins_username'), ['username'])

    with op.batch_alter_table('newsletter_deliveries', schema=None) as batch_op:
        batch_op.alter_column('newsletter_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('newsletter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('last_update_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('datetime_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delta_content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('html_content', sa.Text(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('datetime_added',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('sent_to_users',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_newsletter_list_last_update_by_admins'), 'admins', ['last_update_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_newsletter_list_created_by_admins'), 'admins', ['created_by'], ['id'])
        batch_op.drop_column('email_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_content', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_newsletter_list_created_by_admins'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_newsletter_list_last_update_by_admins'), type_='foreignkey')
        batch_op.alter_column('sent_to_users',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('datetime_added',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('html_content')
        batch_op.drop_column('delta_content')
        batch_op.drop_column('datetime_updated')
        batch_op.drop_column('last_update_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('newsletter_deliveries', schema=None) as batch_op:
        batch_op.alter_column('newsletter_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_admins_username'), type_='unique')

    # ### end Alembic commands ###
