"""Added hash column for image database

Revision ID: b519d2002748
Revises: c2c0fc0c218c
Create Date: 2026-05-03 15:34:14.204992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b519d2002748'
down_revision = 'c2c0fc0c218c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_images_hash'), ['hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_images_hash'), type_='unique')
        batch_op.drop_column('hash')

    # ### end Alembic commands ###
