"""Added image class to store image name and metadata

Revision ID: c2c0fc0c218c
Revises: c4a65f269753
Create Date: 2026-05-03 14:49:07.387813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c0fc0c218c'
down_revision = 'c4a65f269753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('filename', sa.String(length=36), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('filename', name=op.f('pk_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
