"""added title variable for newsletters

Revision ID: c4a65f269753
Revises: 3105794bae58
Create Date: 2026-04-29 17:15:03.015486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a65f269753'
down_revision = '3105794bae58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_list', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
